'use client';

import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, FileEdit, Send, XCircle } from 'lucide-react';
import { api, apiMessage } from '@/shared/services/api';

type Article = { id:string; slug:string; titleFa:string; titleEn:string; excerptFa:string; excerptEn:string; contentFa:string; contentEn:string; status:string; rejectionReason?:string; updatedAt:string; author?:{name?:string} };
const labels:Record<string,string>={DRAFT:'پیش‌نویس',PENDING_REVIEW:'در انتظار بررسی',APPROVED:'تأییدشده',REJECTED:'نیازمند اصلاح',PUBLISHED:'منتشرشده',ARCHIVED:'بایگانی'};

export function InstructorArticleWorkspace(){
  const qc=useQueryClient(), query=useQuery({queryKey:['instructor-articles'],queryFn:()=>api<Article[]>('/blog/instructor/posts')}), [open,setOpen]=useState(false), [error,setError]=useState('');
  const create=useMutation({mutationFn:(body:Record<string,string>)=>api('/blog/instructor/posts',{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>{setOpen(false);void qc.invalidateQueries({queryKey:['instructor-articles']})},onError:e=>setError(apiMessage(e,'ذخیره مقاله ناموفق بود.'))});
  const submit=useMutation({mutationFn:(id:string)=>api(`/blog/posts/${id}/submit`,{method:'POST'}),onSuccess:()=>void qc.invalidateQueries({queryKey:['instructor-articles']})});
  function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');const values=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;create.mutate(values)}
  return <section><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-black text-purple">مجله مدرس</p><h1 className="mt-2 text-3xl font-black">مقاله‌های من</h1><p className="mt-2 text-sm text-muted">مقاله را آماده کنید و برای بررسی مدیر بفرستید.</p></div><button onClick={()=>setOpen(x=>!x)} className="primary-button"><FileEdit size={18}/>{open?'بستن فرم':'مقاله جدید'}</button></div>{open&&<form onSubmit={save} className="panel-card mt-7 grid gap-4 p-6 md:grid-cols-2"><Field name="titleFa" label="عنوان فارسی"/><Field name="titleEn" label="عنوان انگلیسی" dir="ltr"/><Field name="slug" label="Slug" dir="ltr"/><Field name="coverImage" label="نشانی تصویر کاور" dir="ltr" optional/><Field name="excerptFa" label="خلاصه فارسی" area/><Field name="excerptEn" label="خلاصه انگلیسی" area dir="ltr"/><div className="md:col-span-2"><Field name="contentFa" label="محتوای فارسی" area large/></div><div className="md:col-span-2"><Field name="contentEn" label="محتوای انگلیسی" area large dir="ltr"/></div>{error&&<p role="alert" className="md:col-span-2 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<button disabled={create.isPending} className="primary-button justify-center md:col-span-2">{create.isPending?'در حال ذخیره...':'ذخیره پیش‌نویس'}</button></form>}<ArticleStates loading={query.isLoading} error={query.isError} retry={()=>query.refetch()}>{query.data?.map(article=><article key={article.id} className="panel-card p-5"><div className="flex items-start justify-between gap-4"><div><span className={`status-pill ${article.status==='REJECTED'?'status-warning':article.status==='PUBLISHED'?'status-success':'status-info'}`}>{labels[article.status]??article.status}</span><h2 className="mt-3 text-lg font-black">{article.titleFa}</h2><p className="mt-2 line-clamp-2 text-sm leading-7 text-muted">{article.excerptFa}</p></div><FileEdit className="shrink-0 text-purple"/></div>{article.rejectionReason&&<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>دلیل بازگشت:</strong> {article.rejectionReason}</div>}{['DRAFT','REJECTED'].includes(article.status)&&<button disabled={submit.isPending} onClick={()=>submit.mutate(article.id)} className="secondary-button mt-5"><Send size={16}/>ارسال برای بررسی</button>}</article>)}</ArticleStates></section>
}

export function AdminArticleReviewWorkspace(){
  const qc=useQueryClient(), query=useQuery({queryKey:['article-review-queue'],queryFn:()=>api<Article[]>('/blog/review/queue')}), [error,setError]=useState('');
  const action=useMutation({mutationFn:({id,type,reason}:{id:string;type:'approve'|'reject';reason?:string})=>api(`/blog/posts/${id}/${type}`,{method:'POST',body:type==='reject'?JSON.stringify({reason}):undefined}),onSuccess:()=>void qc.invalidateQueries({queryKey:['article-review-queue']}),onError:e=>setError(apiMessage(e,'ثبت تصمیم ناموفق بود.'))});
  function reject(id:string){const reason=window.prompt('دلیل دقیق رد مقاله را وارد کنید (حداقل ۱۰ نویسه):')?.trim();if(reason&&reason.length>=10)action.mutate({id,type:'reject',reason})}
  return <section><p className="text-sm font-black text-purple">گردش کار محتوا</p><h1 className="mt-2 text-3xl font-black">صف بررسی مجله</h1><p className="mt-2 text-sm text-muted">قدیمی‌ترین مقاله‌های منتظر بررسی در ابتدای صف هستند.</p>{error&&<p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<ArticleStates loading={query.isLoading} error={query.isError} retry={()=>query.refetch()} empty="مقاله‌ای در انتظار بررسی نیست.">{query.data?.map(article=><article key={article.id} className="panel-card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><span className="status-pill status-warning">در انتظار بررسی</span><h2 className="mt-3 text-xl font-black">{article.titleFa}</h2><p className="mt-1 text-xs text-muted">نویسنده: {article.author?.name??'مدرس'}</p></div><span className="latin text-xs text-muted">/{article.slug}</span></div><p className="mt-5 text-sm leading-7 text-muted">{article.excerptFa}</p><details className="mt-4 rounded-xl bg-canvas p-4"><summary className="cursor-pointer font-bold">پیش‌نمایش محتوا</summary><p className="mt-4 whitespace-pre-wrap text-sm leading-8">{article.contentFa}</p></details><div className="mt-5 flex flex-wrap gap-3"><button disabled={action.isPending} onClick={()=>action.mutate({id:article.id,type:'approve'})} className="primary-button"><CheckCircle2 size={17}/>تأیید مقاله</button><button disabled={action.isPending} onClick={()=>reject(article.id)} className="secondary-button text-red-600"><XCircle size={17}/>رد با دلیل</button></div></article>)}</ArticleStates></section>
}

function Field({name,label,area,large,dir,optional}:{name:string;label:string;area?:boolean;large?:boolean;dir?:'ltr';optional?:boolean}){return <label className="grid gap-2 text-sm font-bold">{label}{area?<textarea required={!optional} name={name} dir={dir} rows={large?8:3} className="input resize-y"/>:<input required={!optional} name={name} dir={dir} className="input"/>}</label>}
function ArticleStates({loading,error,retry,empty='هنوز مقاله‌ای ندارید.',children}:{loading:boolean;error:boolean;retry:()=>unknown;empty?:string;children:React.ReactNode}){if(loading)return <div className="mt-7 grid gap-4"><div className="skeleton h-44 rounded-2xl"/><div className="skeleton h-44 rounded-2xl"/></div>;if(error)return <div role="alert" className="mt-7 rounded-2xl bg-red-50 p-5 text-red-700">دریافت مقاله‌ها ناموفق بود. <button onClick={retry} className="font-bold underline">تلاش دوباره</button></div>;const list=Array.isArray(children)?children.filter(Boolean):children;return <div className="mt-7 grid gap-4">{Array.isArray(list)&&!list.length?<div className="rounded-2xl border border-dashed hairline p-10 text-center text-muted">{empty}</div>:children}</div>}
