import Image from 'next/image';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,BarChart3,Check,ClipboardCheck,Headphones,PenTool,Target,Users,Video} from 'lucide-react';
import {Eyebrow,Footer,Header} from '@/components/site';
import {TeacherCard} from '@/components/teacher-card';
import {publicApi,type Paginated,type PublicTeacher} from '@/lib/api';
import {requestLocale} from '@/lib/server-locale';
import {localePath} from '@/lib/i18n';

export const dynamic='force-dynamic';

export default async function Home(){
 const locale=await requestLocale(),fa=locale==='fa',p=(href:string)=>localePath(href,locale),Arrow=fa?ArrowLeft:ArrowRight;
 let featured:PublicTeacher[]=[],total=0,unavailable=false;
 try{const response=await publicApi<Paginated<PublicTeacher>>('/teachers?limit=3&sort=rating',{cache:'no-store'});featured=response.data;total=response.total}catch{unavailable=true}
 const c=fa?{
  eyebrow:'مسیر هوشمند آیلتس',titleA:'نمره هدفت اتفاقی نیست؛',titleB:'با مدرس درست به آن برس.',lead:'با تعیین سطح دقیق و تطبیق هوشمند، مدرس مناسب هدف، بودجه و زمانت را پیدا کن و با یک برنامه روشن پیش برو.',match:'مدرس مناسبم را پیدا کن',test:'شروع تعیین سطح',verified:`${total.toLocaleString('fa-IR')} مدرس تأییدشده`,transparent:'انتخاب شفاف بر اساس سطح و هدف',personal:'برنامه یادگیری شخصی',stepsEyebrow:'مسیر سه‌مرحله‌ای',stepsTitle:'از شناخت سطح تا شروع کلاس',featured:'مدرس‌های منتخب',all:'مشاهده همه مدرس‌ها',offline:'سرویس مدرس‌ها در دسترس نیست. اتصال API و دیتابیس را بررسی کنید.',none:'در حال حاضر مدرس تأییدشده‌ای برای نمایش وجود ندارد.',assessmentEyebrow:'شروع درست',assessmentTitle:'اول سطح واقعی‌ات را بشناس',assessmentBody:'با آزمون چهارمهارتی، نقاط قوت و ضعف خودت را ببین و پیشنهاد مدرس دقیق‌تری دریافت کن.',assessmentCta:'شروع آزمون تعیین سطح',services:'هر چیزی که برای پیشرفت لازم داری',finalSmall:'آماده‌ای مسیرت را شروع کنی؟',finalTitle:'مدرس مناسب، برنامه روشن، پیشرفت واقعی.',finalCta:'شروع تطبیق هوشمند'
 }:{
  eyebrow:'A smarter IELTS journey',titleA:'Your target band is not an accident.',titleB:'Reach it with the right teacher.',lead:'Assess your level, match with a verified teacher for your goal, budget, and schedule, then move forward with a clear learning plan.',match:'Find my teacher',test:'Take the placement test',verified:`${total.toLocaleString('en-US')} verified teachers`,transparent:'Transparent matching by level and goal',personal:'A personal learning plan',stepsEyebrow:'A clear three-step path',stepsTitle:'From assessment to your first class',featured:'Featured teachers',all:'View all teachers',offline:'The teacher service is unavailable. Check the API and database connection.',none:'No approved teachers are available right now.',assessmentEyebrow:'Start with clarity',assessmentTitle:'Know exactly where you stand',assessmentBody:'Assess all four skills, understand your strengths and gaps, and receive more accurate teacher recommendations.',assessmentCta:'Start the placement test',services:'Everything you need to make progress',finalSmall:'Ready to begin?',finalTitle:'The right teacher, a clear plan, real progress.',finalCta:'Start smart matching'
 };
 const steps=fa?[[ClipboardCheck,'تعیین سطح','سطح دقیق شما در چهار مهارت مشخص می‌شود.'],[Users,'تطبیق هوشمند','مدرس‌های تأییدشده متناسب با نیازتان رتبه‌بندی می‌شوند.'],[Headphones,'جلسه آزمایشی','قبل از انتخاب نهایی، مدرس و روش تدریس را ارزیابی کنید.']]:[[ClipboardCheck,'Assess your level','Measure your current ability across all four IELTS skills.'],[Users,'Smart matching','Rank verified teachers against your goals and preferences.'],[Headphones,'Book a trial','Meet the teacher and evaluate the teaching fit before committing.']];
 const services=fa?[[Target,'برنامه شخصی','برنامه متناسب با هدف، زمان و نقاط ضعف شما.'],[Video,'کلاس آنلاین','جلسه زنده با زمان‌بندی منعطف و لینک امن.'],[BarChart3,'ارزیابی چهار مهارت','نتیجه و بازخورد Reading، Listening، Writing و Speaking.'],[PenTool,'تکلیف و بازخورد','تکلیف، ارسال پاسخ و بازخورد مدرس در یک مسیر منظم.']]:[[Target,'Personal plan','A plan built around your goal, time, and weak skills.'],[Video,'Live classes','Secure live sessions with flexible scheduling.'],[BarChart3,'Four-skill assessment','Results and feedback for every IELTS skill.'],[PenTool,'Assignments & feedback','Submit work and receive teacher feedback in one place.']];
 return <><Header/><main className="overflow-hidden bg-white"><section className="mx-auto max-w-[1380px] px-5 pb-20 pt-12 lg:px-8 lg:pb-24 lg:pt-20"><div className="grid items-center gap-12 lg:grid-cols-2"><div className="reveal"><Eyebrow>{c.eyebrow}</Eyebrow><h1 className="max-w-3xl text-5xl font-black leading-[1.22] tracking-[-.045em] md:text-6xl xl:text-[68px]">{c.titleA}<br/><span className="brand-text">{c.titleB}</span></h1><p className="mt-7 max-w-2xl text-lg leading-9 text-muted">{c.lead}</p><div className="mt-9 flex flex-wrap gap-3"><Link href={p('/matching')} className="brand-gradient brand-glow flex items-center gap-3 rounded-xl px-7 py-4 font-black text-white">{c.match}<Arrow size={19}/></Link><Link href={p('/placement')} className="flex items-center gap-3 rounded-xl border border-[#cfd5e5] bg-white px-7 py-4 font-black hover:border-purple">{c.test}<PenTool size={18}/></Link></div><div className="mt-10 grid max-w-2xl gap-3 sm:grid-cols-3"><span className="rounded-xl bg-[#f7f8fc] p-4 text-sm font-bold"><Check className="mb-2 text-blue" size={18}/>{c.verified}</span><span className="rounded-xl bg-[#f7f8fc] p-4 text-sm font-bold"><Check className="mb-2 text-purple" size={18}/>{c.transparent}</span><span className="rounded-xl bg-[#f7f8fc] p-4 text-sm font-bold"><Check className="mb-2 text-violet" size={18}/>{c.personal}</span></div></div><div className="relative min-h-[520px] reveal-delay"><div className="absolute inset-10 rounded-full border-2 border-blue/25"/><div className="absolute inset-20 rounded-full border border-purple/20"/><div className="absolute inset-x-10 bottom-0 top-16 overflow-hidden rounded-[42%_42%_20%_20%] bg-gradient-to-br from-[#eef3ff] to-[#eee8ff]"><Image src="/images/lingospeak-student.png" alt={fa?'زبان‌آموز در حال مطالعه':'Student studying English'} fill priority className="object-cover object-[42%_center]"/></div><div className="float-slow panel-card absolute right-0 top-8 w-40 p-5"><p className="text-xs text-muted">{fa?'ارزیابی سطح':'Level assessment'}</p><strong className="mt-2 block text-xl">{fa?'چهار مهارت':'Four skills'}</strong></div><div className="float-delay panel-card absolute left-0 top-32 w-44 p-5"><p className="text-xs text-muted">{fa?'پیشنهاد هوشمند':'Smart recommendation'}</p><strong className="mt-2 block text-xl">{fa?'مدرس مناسب':'The right teacher'}</strong></div><div className="float-slow panel-card absolute bottom-5 right-3 w-48 p-5"><p className="text-xs text-muted">{fa?'مسیر یادگیری':'Learning journey'}</p><strong className="mt-2 block">{fa?'برنامه قابل پیگیری':'Trackable plan'}</strong><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#edf0f6]"><span className="block h-full w-[68%] rounded-full bg-blue"/></div></div></div></div></section>
 <section className="bg-canvas py-24"><div className="mx-auto max-w-[1380px] px-5 lg:px-8"><div className="text-center"><p className="text-sm font-bold text-purple">{c.stepsEyebrow}</p><h2 className="mt-3 text-4xl font-black">{c.stepsTitle}</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{steps.map(([Icon,title,body],i)=>{const I=Icon as typeof ClipboardCheck;return <article key={String(title)} className="surface-card lift relative p-8"><span className="absolute end-6 top-6 grid size-10 place-items-center rounded-full bg-lavender font-black text-purple">{i+1}</span><span className="grid size-14 place-items-center rounded-2xl bg-[#f0f3ff] text-blue"><I size={26}/></span><h3 className="mt-9 text-xl font-black">{String(title)}</h3><p className="mt-4 text-sm leading-7 text-muted">{String(body)}</p></article>})}</div></div></section>
 <section className="py-24"><div className="mx-auto max-w-[1380px] px-5 lg:px-8"><div className="flex items-end justify-between gap-4"><h2 className="text-4xl font-black">{c.featured}</h2><Link href={p('/teachers')} className="flex items-center gap-2 text-sm font-bold text-blue">{c.all}<Arrow size={17}/></Link></div>{unavailable?<div role="alert" className="mt-10 rounded-3xl border border-red-100 bg-red-50 p-6 text-red-800">{c.offline}</div>:featured.length?<div className="mt-10 grid gap-6 lg:grid-cols-3">{featured.map(t=><TeacherCard key={t.id} teacher={t}/>)}</div>:<div className="mt-10 rounded-3xl border border-dashed hairline p-10 text-center text-muted">{c.none}</div>}</div></section>
 <section className="mx-auto max-w-[1380px] px-5 pb-24 lg:px-8"><div className="soft-gradient grid items-center gap-8 overflow-hidden rounded-[30px] border border-violet/15 p-8 md:grid-cols-[.7fr_1.3fr] md:p-12"><div className="relative mx-auto h-52 w-64"><span className="absolute left-8 top-4 grid size-40 place-items-center rounded-[35px] bg-white text-blue shadow-soft"><ClipboardCheck size={78}/></span><span className="absolute bottom-1 right-2 grid size-20 place-items-center rounded-full bg-white text-purple shadow-soft"><Check size={36}/></span></div><div><p className="text-sm font-bold text-purple">{c.assessmentEyebrow}</p><h2 className="mt-3 text-4xl font-black">{c.assessmentTitle}</h2><p className="mt-4 max-w-2xl leading-8 text-muted">{c.assessmentBody}</p><Link href={p('/placement')} className="brand-gradient mt-7 inline-flex items-center gap-3 rounded-xl px-7 py-4 font-black text-white">{c.assessmentCta}<Arrow size={18}/></Link></div></div></section>
 <section className="bg-canvas py-24"><div className="mx-auto max-w-[1380px] px-5 lg:px-8"><h2 className="text-4xl font-black">{c.services}</h2><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([Icon,title,body])=>{const I=Icon as typeof Target;return <article className="surface-card lift p-7" key={String(title)}><I className="text-purple"/><h3 className="mt-6 font-black">{String(title)}</h3><p className="mt-3 text-sm leading-7 text-muted">{String(body)}</p></article>})}</div></div></section>
 <section className="mx-auto max-w-[1380px] px-5 py-24 lg:px-8"><div className="relative overflow-hidden rounded-[28px] bg-navy p-9 text-white md:p-14"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_20%_30%,#7654f6_0,transparent_35%),radial-gradient(circle_at_80%_70%,#315efb_0,transparent_30%)]"/><div className="relative flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-sm text-white/60">{c.finalSmall}</p><h2 className="mt-3 text-4xl font-black">{c.finalTitle}</h2></div><Link href={p('/matching')} className="brand-gradient brand-glow flex items-center gap-3 rounded-xl px-7 py-4 font-black">{c.finalCta}<Arrow/></Link></div></div></section></main><Footer/></>
}
