import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, BarChart3, BookOpen, CalendarDays, CheckCircle2, GraduationCap, Headphones, MessageSquareQuote, ShieldCheck, Sparkles, Star, Target, Users, Video } from 'lucide-react';
import { BlogCard, CourseCard, LanguageCard, TeacherMarketCard } from '@/components/marketplace/cards';
import { Eyebrow, Footer, Header } from '@/components/layout/site';
import { marketplaceService } from '@/lib/marketplace-data';

export const dynamic = 'force-dynamic';

const steps = ['تعیین هدف', 'تعیین سطح', 'انتخاب زبان', 'برنامه شخصی', 'تطبیق با مدرس', 'شروع دوره', 'پایش پیشرفت', 'مشاوره تخصصی', 'رسیدن به هدف'];
const benefits = [[Sparkles, 'تطبیق هوشمند مدرس', 'بر اساس هدف، سطح، بودجه و زمان آزاد شما.'], [Headphones, 'مشاوره تخصصی', 'قبل از شروع، مسیر مناسب را با مشاور آموزشی پیدا کنید.'], [Target, 'برنامه یادگیری شخصی', 'یک برنامه روشن که با ریتم زندگی شما هماهنگ می‌شود.'], [BarChart3, 'پایش و تحلیل پیشرفت', 'گزارش‌های ساده و کاربردی از هر قدم یادگیری.']] as const;
const faqs = [['چگونه می‌توانم در دوره‌ها ثبت‌نام کنم؟', 'زبان و دوره دلخواه را انتخاب کنید، جزئیات را ببینید و ثبت‌نام را آنلاین کامل کنید.'], ['آیا مدرس‌ها تأیید شده‌اند؟', 'بله، هویت، سابقه و مدارک مدرس‌ها پیش از فعال شدن پروفایل بررسی می‌شود.'], ['کلاس‌ها آنلاین هستند یا حضوری؟', 'اغلب کلاس‌ها آنلاین‌اند؛ برخی مدرس‌ها امکان کلاس حضوری را نیز در پروفایل اعلام می‌کنند.'], ['شرایط لغو یا تغییر زمان کلاس چیست؟', 'تا ۲۴ ساعت پیش از جلسه می‌توانید زمان را بدون جریمه تغییر دهید.']];

export default async function Home() {
  const [languages, teachers, courses, posts, statistics] = await Promise.all([marketplaceService.getLanguages(), marketplaceService.getTeachers(), marketplaceService.getCourses(), marketplaceService.getPosts(), marketplaceService.getStatistics()]);
  const statIcons = { students: Users, teachers: GraduationCap, rating: Star, classes: BookOpen };
  return <><Header/><main className="overflow-hidden bg-white">
    <section className="hero-wash"><div className="page-shell grid items-center gap-12 pb-14 pt-10 lg:grid-cols-[1.05fr_.95fr] lg:pb-20 lg:pt-16">
      <div className="reveal"><Eyebrow>یادگیری زبان برای همه</Eyebrow><h1 className="max-w-2xl text-[2.55rem] font-black leading-[1.38] tracking-[-.045em] md:text-6xl">مسیر کامل یادگیری زبان،<br/>تا رسیدن به <span className="brand-text">هدف شما</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-muted md:text-lg">از تعیین سطح تا پیشرفت واقعی؛ با دوره‌های آنلاین، مدرس‌های متخصص و برنامه‌ای که برای زندگی و هدف شما طراحی شده است.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/languages" className="brand-gradient brand-glow inline-flex min-h-13 items-center justify-center gap-3 rounded-xl px-7 font-black text-white">شروع مسیر یادگیری <ArrowLeft size={19}/></Link><Link href="/courses" className="inline-flex min-h-13 items-center justify-center rounded-xl border border-purple/35 bg-white px-7 font-black text-purple hover:bg-lavender">مشاهده دوره‌ها</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-muted"><span className="flex items-center gap-2"><ShieldCheck className="text-purple" size={18}/>مدرس‌های تأییدشده</span><span className="flex items-center gap-2"><Video className="text-purple" size={18}/>کلاس آنلاین تعاملی</span><span className="flex items-center gap-2"><CalendarDays className="text-purple" size={18}/>برنامه منعطف</span></div></div>
      <div className="relative min-h-[470px] reveal-delay lg:min-h-[560px]"><div className="absolute inset-6 overflow-hidden rounded-[36px] bg-gradient-to-br from-indigo-50 to-violet-100 shadow-soft"><Image src="/images/lingospeak-student.png" alt="زبان‌آموز در حال یادگیری زبان با لپ‌تاپ" fill priority sizes="(min-width:1024px) 46vw, 100vw" className="object-cover object-center"/></div><div className="floating-card right-0 top-16"><p>سطح فعلی شما</p><strong>B1 · متوسط</strong><span className="mt-3 block h-1.5 rounded-full bg-indigo-100"><i className="block h-full w-2/3 rounded-full bg-purple"/></span></div><div className="floating-card left-0 top-8"><p>پیشرفت کلی</p><strong className="text-2xl text-purple">۷۲٪</strong></div><div className="floating-card bottom-3 left-4"><p>جلسه بعدی</p><strong>مکالمه فرانسوی</strong><small className="mt-1 block text-muted">شنبه، ساعت ۱۸:۳۰</small></div><div className="floating-card bottom-10 right-0"><p>زبان‌های محبوب</p><strong className="text-xl tracking-[.25em]">🇬🇧 🇩🇪 🇫🇷 🇪🇸</strong></div></div>
    </div></section>
    <section className="page-shell -mt-3 relative z-10"><div className="grid overflow-hidden rounded-2xl border hairline bg-white shadow-soft sm:grid-cols-2 lg:grid-cols-4">{statistics.map((stat)=>{const Icon=statIcons[stat.icon];return <div key={stat.label} className="flex items-center gap-4 border-b hairline p-6 last:border-0 sm:border-l lg:border-b-0"><span className="grid size-12 place-items-center rounded-2xl bg-lavender text-purple"><Icon size={23}/></span><div><strong className="latin text-xl">{stat.value}</strong><p className="mt-1 text-xs text-muted">{stat.label}</p></div></div>})}</div></section>
    <section className="section-space"><div className="page-shell"><div className="section-title"><p>گام‌به‌گام تا تسلط</p><h2>مسیر یادگیری شما، روشن و قابل پیگیری</h2></div><ol className="learning-track">{steps.map((step,i)=><li key={step}><span>{(i+1).toLocaleString('fa-IR')}</span><strong>{step}</strong></li>)}</ol></div></section>
    <section className="bg-canvas section-space"><div className="page-shell"><div className="section-title"><p>چرا LingoSpeak؟</p><h2>همه‌چیز برای یک انتخاب مطمئن</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([Icon,title,body])=><article key={title} className="market-card lift p-6"><span className="grid size-12 place-items-center rounded-2xl bg-lavender text-purple"><Icon size={23}/></span><h3 className="mt-5 font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-muted">{body}</p></article>)}</div></div></section>
    <section className="section-space"><div className="page-shell"><SectionHeading title="زبان مورد علاقه‌ات را انتخاب کن" href="/languages" link="مشاهده همه زبان‌ها"/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{languages.map(x=><LanguageCard key={x.slug} language={x}/>)}</div></div></section>
    <section className="bg-canvas section-space"><div className="page-shell"><SectionHeading title="مدرس‌هایی که با هدف شما هماهنگ‌اند" href="/teachers" link="مشاهده همه مدرس‌ها"/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{teachers.map(x=><TeacherMarketCard key={x.slug} teacher={x}/>)}</div></div></section>
    <section className="section-space"><div className="page-shell"><SectionHeading title="دوره‌های پیشنهادی برای شروع" href="/courses" link="مشاهده همه دوره‌ها"/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{courses.map(x=><CourseCard key={x.slug} course={x}/>)}</div></div></section>
    <section className="page-shell pb-24"><div className="teach-banner"><div className="relative min-h-64 lg:min-h-80"><Image src="/images/auth/register.png" alt="مدرس حرفه‌ای زبان آماده تدریس" fill sizes="(min-width:1024px) 36vw, 100vw" className="object-contain object-bottom"/></div><div className="py-10 lg:py-14"><p className="text-sm font-bold text-purple">به جمع مدرس‌های ما بپیوندید</p><h2 className="mt-3 text-3xl font-black leading-[1.5] md:text-4xl">مدرس زبان هستید؟<br/><span className="brand-text">شاگردهای جدید منتظر شما هستند</span></h2><div className="mt-6 grid gap-3 text-sm sm:grid-cols-2">{['دسترسی به زبان‌آموزان جدید','تعیین برنامه و ظرفیت کلاس‌ها','مدیریت درآمد و جلسات','ساخت پروفایل حرفه‌ای'].map(x=><span key={x} className="flex items-center gap-2"><CheckCircle2 size={17} className="text-purple"/>{x}</span>)}</div><Link href="/teach/register" className="brand-gradient mt-8 inline-flex min-h-12 items-center rounded-xl px-8 font-black text-white">ثبت‌نام به عنوان مدرس</Link></div></div></section>
    <section className="bg-canvas section-space"><div className="page-shell"><SectionHeading title="مجله یادگیری زبان" href="/blog" link="مشاهده همه مقالات"/><div className="mt-9 grid gap-5 md:grid-cols-3">{posts.map(x=><BlogCard key={x.slug} post={x}/>)}</div></div></section>
    <section className="section-space"><div className="page-shell grid gap-10 lg:grid-cols-2"><div><p className="text-sm font-bold text-purple">صدای زبان‌آموزان ما</p><h2 className="mt-3 text-3xl font-black">پیشرفت‌هایی که واقعی‌اند</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{['کلاس‌ها منظم و برنامه دقیقاً متناسب با زمان من بود. بعد از سه ماه بالاخره بدون ترس صحبت می‌کنم.','تطبیق مدرس واقعاً خوب عمل کرد؛ مدرس من هم تخصص آزمون داشت و هم روش تدریسش با من سازگار بود.'].map((q,i)=><blockquote key={q} className="market-card p-6"><MessageSquareQuote className="text-purple"/><p className="mt-4 text-sm leading-7 text-muted">«{q}»</p><footer className="mt-4 font-black">{i?'غزل صالحی':'الهام نادری'} <span className="mr-2 text-amber-400">★★★★★</span></footer></blockquote>)}</div></div><div><p className="text-sm font-bold text-purple">سؤالات متداول</p><h2 className="mt-3 text-3xl font-black">پاسخ کوتاه به سؤال‌های مهم</h2><div className="mt-8 divide-y overflow-hidden rounded-2xl border hairline bg-white">{faqs.map(([q,a],i)=><details key={q} className="group p-5" open={i===0}><summary className="cursor-pointer list-none font-black">{q}<span className="float-left text-purple group-open:rotate-45">＋</span></summary><p className="mt-3 text-sm leading-7 text-muted">{a}</p></details>)}</div></div></div></section>
    <section className="page-shell pb-24"><div className="final-cta"><div><p className="text-sm text-white/70">از امروز شروع کنید</p><h2 className="mt-2 text-3xl font-black">یک زبان تازه، یک دنیای تازه</h2></div><div className="flex flex-wrap gap-3"><Link href="/languages" className="rounded-xl bg-white px-6 py-3 font-black text-purple">مشاهده دوره‌ها</Link><Link href="/teachers" className="rounded-xl border border-white/40 px-6 py-3 font-black text-white">پیدا کردن مدرس</Link></div></div></section>
  </main><Footer/></>;
}

function SectionHeading({title,href,link}:{title:string;href:string;link:string}){return <div className="flex items-end justify-between gap-4"><h2 className="text-2xl font-black md:text-3xl">{title}</h2><Link href={href} className="flex shrink-0 items-center gap-2 text-sm font-black text-purple">{link}<ArrowLeft size={16}/></Link></div>}
