import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, BarChart3, BookOpen, BrainCircuit, CalendarDays, CheckCircle2, GraduationCap, Headphones, Route, ShieldCheck, Sparkles, Target, Timer, Users, Video } from 'lucide-react';
import { BlogCard, CourseCard } from '@/components/marketplace/cards';
import { Eyebrow, Footer, Header } from '@/components/layout/site';
import { publicApi, type Paginated } from '@/shared/services/api';
import type { Course } from '@/lib/marketplace-data';
import type { EducationalLanguage } from '@/features/languages';
import type { PublicTeacher } from '@/features/teacher';
import type { BlogPostsPage } from '@/features/blog/types';
import { LanguageDiscoveryCard } from '@/features/languages/components/language-discovery-card';
import { TeacherCard } from '@/features/teacher/components/teacher-card';
import { requestLocale } from '@/lib/server-locale';
import { formatNumber, localePath } from '@/lib/i18n';
import { logError } from '@/shared/services/error-logger';

export const dynamic = 'force-dynamic';

const EMPTY_TEACHERS: Paginated<PublicTeacher> = { data: [], total: 0, page: 1, totalPages: 0 };
const EMPTY_POSTS: BlogPostsPage = { items: [], page: 1, pageSize: 0 };

// The landing page is what an unauthenticated visitor hits first, so no single
// upstream section may take the whole render down. A freshly seeded database
// legitimately has no teachers, courses, or posts, and a degraded endpoint has
// to degrade to an empty section rather than a 500. The failure is still logged,
// because an unreachable API otherwise renders exactly like an empty database.
function withFallback<T>(endpoint: string, request: Promise<T>, fallback: T): Promise<T> {
  return request.catch((error: unknown) => {
    logError(error, { scope: 'route', name: `home:${endpoint}` });
    return fallback;
  });
}

export default async function Home() {
  const [languages, teacherPage, courses, posts, locale] = await Promise.all([
    withFallback('/languages', publicApi<EducationalLanguage[]>('/languages'), []),
    withFallback('/teachers', publicApi<Paginated<PublicTeacher>>('/teachers?page=1&limit=4&sort=rating'), EMPTY_TEACHERS),
    withFallback('/courses', publicApi<Course[]>('/courses'), []),
    withFallback('/blog/posts', publicApi<BlogPostsPage>('/blog/posts?pageSize=3'), EMPTY_POSTS),
    requestLocale(),
  ]);
  const english = locale === 'en';
  const t = (fa: string, en: string) => english ? en : fa;
  const path = (pathname: string) => localePath(pathname, locale);
  const steps = english
    ? ['Set your goal', 'Check your level', 'Choose a language', 'Build your plan', 'Match with a teacher', 'Start learning', 'Track progress', 'Get guidance', 'Reach your goal']
    : ['تعیین هدف', 'تعیین سطح', 'انتخاب زبان', 'برنامه شخصی', 'تطبیق با مدرس', 'شروع دوره', 'پایش پیشرفت', 'مشاوره تخصصی', 'رسیدن به هدف'];
  const benefits = english
    ? [[Sparkles, 'Thoughtful teacher matching', 'Based on your goals, level, budget, and availability.'], [Headphones, 'Learning guidance', 'Find the right route with an education adviser before you begin.'], [Target, 'A personal learning plan', 'A clear plan that works with your pace and schedule.'], [BarChart3, 'Visible progress', 'Simple, useful insights into every step of your learning.']] as const
    : [[Sparkles, 'تطبیق هوشمند مدرس', 'بر اساس هدف، سطح، بودجه و زمان آزاد شما.'], [Headphones, 'مشاوره تخصصی', 'قبل از شروع، مسیر مناسب را با مشاور آموزشی پیدا کنید.'], [Target, 'برنامه یادگیری شخصی', 'یک برنامه روشن که با ریتم زندگی شما هماهنگ می‌شود.'], [BarChart3, 'پایش و تحلیل پیشرفت', 'گزارش‌های ساده و کاربردی از هر قدم یادگیری.']] as const;
  const faqs = english
    ? [['How do I book a private lesson?', 'Review a teacher profile, choose a lesson and an available time, then read its cancellation policy before confirming.'], ['Are teachers verified?', 'Yes. We only show teachers whose identity, qualifications, and application have passed review.'], ['Are lessons online or in person?', 'Current bookings are for online lessons, with times displayed in your time zone.'], ['Can I cancel or reschedule?', 'The exact terms depend on the policy shown for that booking before you confirm it.']]
    : [['چطور کلاس خصوصی رزرو کنم؟', 'پروفایل مدرس را بررسی کنید، نوع جلسه و زمان آزاد را انتخاب کنید و سیاست لغو همان رزرو را پیش از تأیید ببینید.'], ['آیا مدرس‌ها تأیید شده‌اند؟', 'بله، فقط پروفایل مدرس‌هایی نمایش داده می‌شود که فرایند بررسی هویت، مدارک و تأیید نهایی را گذرانده‌اند.'], ['کلاس‌ها آنلاین هستند یا حضوری؟', 'رزروهای فعلی برای کلاس آنلاین طراحی شده‌اند و زمان جلسه بر اساس منطقه زمانی شما نمایش داده می‌شود.'], ['شرایط لغو یا تغییر زمان کلاس چیست؟', 'شرایط دقیق به سیاست ثبت‌شده هنگام رزرو بستگی دارد و پیش از تأیید نهایی به شما نمایش داده می‌شود.']];
  const teachers = teacherPage?.data ?? [];
  const postItems = posts?.items ?? [];
  const statistics = [
    { label: t('زبان فعال', 'Active languages'), value: languages.length, icon: GraduationCap },
    { label: t('مدرس تأییدشده', 'Verified teachers'), value: teacherPage?.total ?? 0, icon: Users },
    { label: t('دوره منتشرشده', 'Published courses'), value: courses.length, icon: BookOpen },
    { label: t('مقاله تازه', 'Recent articles'), value: postItems.length, icon: Headphones },
  ];
  return <><Header/><main className="overflow-hidden bg-white">
    <section className="hero-wash"><div className="page-shell grid items-center gap-12 pb-14 pt-10 lg:grid-cols-[1.05fr_.95fr] lg:pb-20 lg:pt-16">
      <div className="reveal"><Eyebrow>{t('یادگیری زبان برای همه', 'Language learning built around you')}</Eyebrow><h1 className="max-w-2xl text-[2.55rem] font-black leading-[1.38] tracking-[-.045em] md:text-6xl">{t('مسیر کامل یادگیری زبان،', 'A complete route to fluency,')}<br/>{t('تا رسیدن به ', 'shaped around ')}<span className="brand-text">{t('هدف شما', 'your goal')}</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-muted md:text-lg">{t('از تعیین سطح تا پیشرفت واقعی؛ با دوره‌های آنلاین، مدرس‌های متخصص و برنامه‌ای که برای زندگی و هدف شما طراحی شده است.', 'From placement to visible progress, learn through online courses, specialist teachers, and a plan designed around your life.')}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href={path('/languages')} className="brand-gradient brand-glow inline-flex min-h-13 items-center justify-center gap-3 rounded-xl px-7 font-black text-white">{t('شروع مسیر یادگیری', 'Start your learning route')} <ArrowLeft className={english ? 'rotate-180' : undefined} size={19}/></Link><Link href={path('/courses')} className="inline-flex min-h-13 items-center justify-center rounded-xl border border-purple/35 bg-white px-7 font-black text-purple hover:bg-lavender">{t('مشاهده دوره‌ها', 'Browse courses')}</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold text-muted"><span className="flex items-center gap-2"><ShieldCheck className="text-purple" size={18}/>{t('مدرس‌های تأییدشده', 'Verified teachers')}</span><span className="flex items-center gap-2"><Video className="text-purple" size={18}/>{t('کلاس آنلاین تعاملی', 'Interactive online lessons')}</span><span className="flex items-center gap-2"><CalendarDays className="text-purple" size={18}/>{t('برنامه منعطف', 'Flexible scheduling')}</span></div></div>
      <div className="relative min-h-[470px] reveal-delay lg:min-h-[560px]"><div className="absolute inset-6 overflow-hidden rounded-[36px] bg-gradient-to-br from-indigo-50 to-violet-100 shadow-soft"><Image src="/images/lingospeak-student.png" alt={t('زبان‌آموز در حال یادگیری زبان با لپ‌تاپ', 'A language learner studying on a laptop')} fill priority sizes="(min-width:1024px) 46vw, 100vw" className="object-cover object-center"/></div><div className="floating-card right-0 top-16"><p>{t('شروع دقیق‌تر', 'Start at the right level')}</p><strong>{t('تعیین سطح CEFR', 'CEFR placement')}</strong></div><div className="floating-card left-0 top-8"><p>{t('زبان‌های فعال', 'Active languages')}</p><strong className="text-2xl text-purple">{formatNumber(languages.length, locale)}</strong></div><div className="floating-card bottom-3 left-4"><p>{t('انتخاب مطمئن', 'Choose with confidence')}</p><strong>{t('مدرس تأییدشده', 'Verified teachers')}</strong></div><div className="floating-card bottom-10 right-0"><p>{t('برنامه کلاس', 'Lesson times')}</p><strong>{t('بر اساس زمان شما', 'Built around you')}</strong></div></div>
    </div></section>
    <section className="page-shell -mt-3 relative z-10"><div className="grid overflow-hidden rounded-2xl border hairline bg-white shadow-soft sm:grid-cols-2 lg:grid-cols-4">{statistics.map((stat)=>{const Icon=stat.icon;return <div key={stat.label} className="flex items-center gap-4 border-b hairline p-6 last:border-0 sm:border-l lg:border-b-0"><span className="grid size-12 place-items-center rounded-2xl bg-lavender text-purple"><Icon size={23}/></span><div><strong className="text-xl">{formatNumber(stat.value, locale)}</strong><p className="mt-1 text-xs text-muted">{stat.label}</p></div></div>})}</div></section>
    <section className="section-space"><div className="page-shell"><div className="section-title"><p>{t('گام‌به‌گام تا تسلط', 'A practical route to fluency')}</p><h2>{t('مسیر یادگیری شما، روشن و قابل پیگیری', 'A learning route you can understand and track')}</h2></div><ol className="learning-track">{steps.map((step,i)=><li key={step}><span>{formatNumber(i+1, locale)}</span><strong>{step}</strong></li>)}</ol></div></section>
    <section className="bg-canvas section-space"><div className="page-shell"><div className="section-title"><p>{t('چرا LingoSpeak؟', 'Why LingoSpeak?')}</p><h2>{t('همه‌چیز برای یک انتخاب مطمئن', 'Everything you need to choose with confidence')}</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(([Icon,title,body])=><article key={title} className="market-card lift p-6"><span className="grid size-12 place-items-center rounded-2xl bg-lavender text-purple"><Icon size={23}/></span><h3 className="mt-5 font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-muted">{body}</p></article>)}</div></div></section>
    <section className="section-space"><div className="page-shell"><div className="placement-banner"><div className="relative z-10 max-w-2xl"><p className="text-sm font-black text-[#9ce8d0]">{t('آزمون استاندارد CEFR', 'CEFR-aligned placement')}</p><h2 className="mt-3 text-3xl font-black leading-[1.5] text-white md:text-5xl">{t('نقطه شروع درست را پیدا کن', 'Find the right place to start')}</h2><p className="mt-4 max-w-xl leading-8 text-white/72">{t('با یک ارزیابی مرحله‌ای، سطح فعلی‌ات از A1 تا C2 مشخص می‌شود و دوره‌هایی را می‌بینی که دقیقاً با توانایی و هدف تو هماهنگ‌اند.', 'A structured assessment identifies your current level from A1 to C2, then points you to learning options suited to your skills and goals.')}</p><div className="mt-7 flex flex-wrap gap-5 text-sm font-bold text-white/85"><span className="flex items-center gap-2"><Timer size={18}/>{t('حدود ۲۰ دقیقه', 'About 20 minutes')}</span><span className="flex items-center gap-2"><BrainCircuit size={18}/>{t('ارزیابی چندمهارتی', 'Multiple skills')}</span><span className="flex items-center gap-2"><Route size={18}/>{t('پیشنهاد مسیر یادگیری', 'A suggested learning route')}</span></div><Link href={path('/placement')} className="mt-8 inline-flex min-h-13 items-center gap-3 rounded-xl bg-white px-7 font-black text-[#24216f] shadow-xl">{t('شروع تعیین سطح', 'Start placement')} <ArrowLeft className={english ? 'rotate-180' : undefined} size={19}/></Link></div><div className="cefr-orbit" aria-hidden="true">{['A1','A2','B1','B2','C1','C2'].map((level,index)=><span key={level} style={{'--i':index} as React.CSSProperties}>{level}</span>)}</div></div></div></section>
    {languages.length>0&&<section className="section-space"><div className="page-shell"><SectionHeading title={t('زبان مورد علاقه‌ات را انتخاب کن', 'Choose the language you want to learn')} href={path('/languages')} link={t('مشاهده همه زبان‌ها', 'View all languages')} english={english}/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{languages.slice(0,4).map(x=><LanguageDiscoveryCard key={x.id} language={x} locale={locale}/>)}</div></div></section>}
    {teachers.length>0&&<section className="bg-canvas section-space"><div className="page-shell"><SectionHeading title={t('مدرس‌هایی که با هدف شما هماهنگ‌اند', 'Teachers who fit your goals')} href={path('/teachers')} link={t('مشاهده همه مدرس‌ها', 'View all teachers')} english={english}/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{teachers.map(x=><TeacherCard key={x.id} teacher={x}/>)}</div></div></section>}
    {courses.length>0&&<section className="section-space"><div className="page-shell"><SectionHeading title={t('دوره‌های پیشنهادی برای شروع', 'Courses to get you started')} href={path('/courses')} link={t('مشاهده همه دوره‌ها', 'View all courses')} english={english}/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{courses.slice(0,4).map(x=><CourseCard key={x.slug} course={x}/>)}</div></div></section>}
    <section className="page-shell pb-24"><div className="teach-banner"><div className="relative min-h-64 lg:min-h-80"><Image src="/images/auth/register.png" alt={t('مدرس حرفه‌ای زبان آماده تدریس', 'A professional language teacher ready to teach')} fill sizes="(min-width:1024px) 36vw, 100vw" className="object-contain object-bottom"/></div><div className="py-10 lg:py-14"><p className="text-sm font-bold text-purple">{t('به جمع مدرس‌های ما بپیوندید', 'Teach with LingoSpeak')}</p><h2 className="mt-3 text-3xl font-black leading-[1.5] md:text-4xl">{t('مدرس زبان هستید؟', 'Are you a language teacher?')}<br/><span className="brand-text">{t('شاگردهای جدید منتظر شما هستند', 'Meet learners looking for your expertise')}</span></h2><div className="mt-6 grid gap-3 text-sm sm:grid-cols-2">{(english ? ['Reach new learners','Set your schedule and capacity','Manage lessons and earnings','Build a professional profile'] : ['دسترسی به زبان‌آموزان جدید','تعیین برنامه و ظرفیت کلاس‌ها','مدیریت درآمد و جلسات','ساخت پروفایل حرفه‌ای']).map(x=><span key={x} className="flex items-center gap-2"><CheckCircle2 size={17} className="text-purple"/>{x}</span>)}</div><Link href={path('/teach/register')} className="brand-gradient mt-8 inline-flex min-h-12 items-center rounded-xl px-8 font-black text-white">{t('ثبت‌نام به عنوان مدرس', 'Apply to teach')}</Link></div></div></section>
    {postItems.length>0&&<section className="bg-canvas section-space"><div className="page-shell"><SectionHeading title={t('مجله یادگیری زبان', 'Language learning magazine')} href={path('/blog')} link={t('مشاهده همه مقالات', 'View all articles')} english={english}/><div className="mt-9 grid gap-5 md:grid-cols-3">{postItems.map(x=><BlogCard key={x.slug} post={{slug:x.slug,category:english ? (x.category?.nameEn??'Learning') : (x.category?.nameFa??'یادگیری'),title:english ? x.titleEn : x.titleFa,excerpt:english ? x.excerptEn : x.excerptFa,date:t('مجله لینگواسپیک', 'LingoSpeak magazine'),readTime:t('مطالعه مقاله', 'Read article'),image:x.coverImage??'/images/lingospeak-student.png'}}/>)}</div></div></section>}
    <section className="section-space"><div className="page-shell max-w-4xl"><div className="text-center"><p className="text-sm font-bold text-purple">{t('سؤالات متداول', 'Frequently asked questions')}</p><h2 className="mt-3 text-3xl font-black">{t('پاسخ روشن پیش از شروع', 'Clear answers before you begin')}</h2></div><div className="mt-8 divide-y overflow-hidden rounded-2xl border hairline bg-white">{faqs.map(([q,a],i)=><details key={q} className="group p-5" open={i===0}><summary className="cursor-pointer list-none font-black">{q}<span className={english ? 'float-right text-purple group-open:rotate-45' : 'float-left text-purple group-open:rotate-45'}>＋</span></summary><p className="mt-3 text-sm leading-7 text-muted">{a}</p></details>)}</div></div></section>
    <section className="page-shell pb-24"><div className="final-cta"><div><p className="text-sm text-white/70">{t('از امروز شروع کنید', 'Start today')}</p><h2 className="mt-2 text-3xl font-black">{t('یک زبان تازه، یک دنیای تازه', 'A new language opens a new world')}</h2></div><div className="flex flex-wrap gap-3"><Link href={path('/courses')} className="rounded-xl bg-white px-6 py-3 font-black text-purple">{t('مشاهده دوره‌ها', 'Browse courses')}</Link><Link href={path('/teachers')} className="rounded-xl border border-white/40 px-6 py-3 font-black text-white">{t('پیدا کردن مدرس', 'Find a teacher')}</Link></div></div></section>
  </main><Footer/></>;
}

function SectionHeading({title,href,link,english}:{title:string;href:string;link:string;english:boolean}){return <div className="flex items-end justify-between gap-4"><h2 className="text-2xl font-black md:text-3xl">{title}</h2><Link href={href} className="flex shrink-0 items-center gap-2 text-sm font-black text-purple">{link}<ArrowLeft className={english ? 'rotate-180' : undefined} size={16}/></Link></div>}
