// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[slug]" | "/admin" | "/admin/[section]" | "/auth" | "/blog" | "/blog/[slug]" | "/checkout" | "/courses" | "/courses/[slug]" | "/dashboard" | "/dashboard/[section]" | "/en" | "/en/[slug]" | "/forgot-password" | "/languages" | "/languages/[slug]" | "/login" | "/matching" | "/panel" | "/payment/development" | "/payment/failure" | "/payment/pending" | "/payment/success" | "/placement" | "/register" | "/reset-password" | "/teach" | "/teach/register" | "/teacher-apply" | "/teacher-panel" | "/teacher-panel/[section]" | "/teachers" | "/teachers/[id]" | "/test/device-check" | "/test/session" | "/verify-code"
type PageRoutes = never
type LayoutRoutes = "/" | "/auth" | "/blog" | "/checkout" | "/courses" | "/languages" | "/payment/development" | "/teachers" | "/test/session"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/[slug]": { "slug": string; }
  "/admin": {}
  "/admin/[section]": { "section": string; }
  "/auth": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/checkout": {}
  "/courses": {}
  "/courses/[slug]": { "slug": string; }
  "/dashboard": {}
  "/dashboard/[section]": { "section": string; }
  "/en": {}
  "/en/[slug]": { "slug": string; }
  "/forgot-password": {}
  "/languages": {}
  "/languages/[slug]": { "slug": string; }
  "/login": {}
  "/matching": {}
  "/panel": {}
  "/payment/development": {}
  "/payment/failure": {}
  "/payment/pending": {}
  "/payment/success": {}
  "/placement": {}
  "/register": {}
  "/reset-password": {}
  "/teach": {}
  "/teach/register": {}
  "/teacher-apply": {}
  "/teacher-panel": {}
  "/teacher-panel/[section]": { "section": string; }
  "/teachers": {}
  "/teachers/[id]": { "id": string; }
  "/test/device-check": {}
  "/test/session": {}
  "/verify-code": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/auth": never
  "/blog": never
  "/checkout": never
  "/courses": never
  "/languages": never
  "/payment/development": never
  "/teachers": never
  "/test/session": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
