// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../src/app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/courses/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/courses/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/courses">> = Specific
  const handler = {} as typeof import("../../src/app/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/en/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/en/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/en/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/en/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/en">> = Specific
  const handler = {} as typeof import("../../src/app/en/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/languages/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/languages/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/languages/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/languages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/languages">> = Specific
  const handler = {} as typeof import("../../src/app/languages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/matching/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/matching">> = Specific
  const handler = {} as typeof import("../../src/app/matching/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/panel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/panel">> = Specific
  const handler = {} as typeof import("../../src/app/panel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/development/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/development">> = Specific
  const handler = {} as typeof import("../../src/app/payment/development/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/failure/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/failure">> = Specific
  const handler = {} as typeof import("../../src/app/payment/failure/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/pending/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/pending">> = Specific
  const handler = {} as typeof import("../../src/app/payment/pending/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/success">> = Specific
  const handler = {} as typeof import("../../src/app/payment/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/placement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/placement">> = Specific
  const handler = {} as typeof import("../../src/app/placement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teach/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teach">> = Specific
  const handler = {} as typeof import("../../src/app/teach/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teach/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teach/register">> = Specific
  const handler = {} as typeof import("../../src/app/teach/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teacher-apply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher-apply">> = Specific
  const handler = {} as typeof import("../../src/app/teacher-apply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teacher-panel/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher-panel/[section]">> = Specific
  const handler = {} as typeof import("../../src/app/teacher-panel/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teacher-panel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher-panel">> = Specific
  const handler = {} as typeof import("../../src/app/teacher-panel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teachers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teachers/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/teachers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teachers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teachers">> = Specific
  const handler = {} as typeof import("../../src/app/teachers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test/device-check/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/device-check">> = Specific
  const handler = {} as typeof import("../../src/app/test/device-check/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test/session/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test/session">> = Specific
  const handler = {} as typeof import("../../src/app/test/session/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-code">> = Specific
  const handler = {} as typeof import("../../src/app/verify-code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../src/app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/courses/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/courses">> = Specific
  const handler = {} as typeof import("../../src/app/courses/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/languages/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/languages">> = Specific
  const handler = {} as typeof import("../../src/app/languages/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/development/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/payment/development">> = Specific
  const handler = {} as typeof import("../../src/app/payment/development/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/teachers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/teachers">> = Specific
  const handler = {} as typeof import("../../src/app/teachers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/test/session/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/test/session">> = Specific
  const handler = {} as typeof import("../../src/app/test/session/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
