export type PlacementLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1';

export type PlacementQuestionSeed = {
  level: PlacementLevel;
  prompt: string;
  choices: string[];
  answerKey: number;
};

const english: PlacementQuestionSeed[] = [
  { level: 'A1', prompt: 'My sister ___ a student.', choices: ['am', 'is', 'are', 'be'], answerKey: 1 },
  { level: 'A1', prompt: 'We ___ in Tehran.', choices: ['live', 'lives', 'living', 'are live'], answerKey: 0 },
  { level: 'A1', prompt: 'He ___ coffee every morning.', choices: ['drink', 'drinks', 'drinking', 'drank'], answerKey: 1 },
  { level: 'A1', prompt: 'There ___ two chairs in the room.', choices: ['is', 'are', 'has', 'be'], answerKey: 1 },
  { level: 'A1', prompt: 'I don’t have ___ brothers.', choices: ['some', 'much', 'any', 'a'], answerKey: 2 },
  {
    level: 'A1',
    prompt: '“How often do you exercise?”',
    choices: ['In the gym.', 'Three times a week.', 'For yesterday.', 'At home yesterday.'],
    answerKey: 1,
  },
  { level: 'A2', prompt: 'I ___ my homework yet.', choices: ['didn’t finish', 'haven’t finished', 'don’t finish', 'wasn’t finishing'], answerKey: 1 },
  { level: 'A2', prompt: 'They ___ dinner when I called them.', choices: ['had', 'were having', 'have', 'are having'], answerKey: 1 },
  { level: 'A2', prompt: 'We’re going ___ a new car next year.', choices: ['buy', 'buying', 'to buy', 'bought'], answerKey: 2 },
  { level: 'A2', prompt: 'You ___ smoke here. It’s prohibited.', choices: ['don’t have to', 'mustn’t', 'couldn’t', 'wouldn’t'], answerKey: 1 },
  { level: 'A2', prompt: 'I’ve lived here ___ 2022.', choices: ['for', 'since', 'during', 'from'], answerKey: 1 },
  { level: 'A2', prompt: 'Can you ___ me a favor?', choices: ['make', 'do', 'give', 'take'], answerKey: 1 },
  { level: 'B1', prompt: 'If I ___ more free time, I would learn Spanish.', choices: ['have', 'had', 'will have', 'would have'], answerKey: 1 },
  { level: 'B1', prompt: 'This is the best restaurant I ___ to.', choices: ['have ever been', 'ever went', 'was ever', 'have ever go'], answerKey: 0 },
  { level: 'B1', prompt: 'The woman ___ lives next door is a doctor.', choices: ['which', 'whose', 'who', 'where'], answerKey: 2 },
  { level: 'B1', prompt: 'When I was younger, I ___ play football every weekend.', choices: ['use to', 'used to', 'was used to', 'am used to'], answerKey: 1 },
  { level: 'B1', prompt: 'We had to ___ the meeting because the manager was ill.', choices: ['take off', 'put off', 'turn off', 'give off'], answerKey: 1 },
  {
    level: 'B1',
    prompt: 'Jane has recently started cycling to work instead of driving. She says it saves money and helps her stay fit. However, she still drives when the weather is bad. Why does Jane usually cycle to work?',
    choices: ['She doesn’t own a car.', 'It saves money and keeps her fit.', 'It is always faster.', 'She dislikes driving.'],
    answerKey: 1,
  },
  { level: 'B2', prompt: 'If I ___ about the traffic, I would have left earlier.', choices: ['knew', 'had known', 'would know', 'have known'], answerKey: 1 },
  { level: 'B2', prompt: 'By the time we arrived, the film ___.', choices: ['already started', 'has already started', 'had already started', 'was already start'], answerKey: 2 },
  { level: 'B2', prompt: 'She denied ___ the confidential information.', choices: ['reveal', 'to reveal', 'revealing', 'revealed'], answerKey: 2 },
  { level: 'B2', prompt: 'The new bridge ___ by the end of next year.', choices: ['will complete', 'will have completed', 'will have been completed', 'has completed'], answerKey: 2 },
  { level: 'B2', prompt: 'His argument was very ___ and supported by strong evidence.', choices: ['reluctant', 'compelling', 'scarce', 'casual'], answerKey: 1 },
  {
    level: 'B2',
    prompt: 'Some employees initially resisted working from home because they feared it would reduce productivity. Nevertheless, several studies found that employees could be equally or even more productive when working remotely. What is the main idea?',
    choices: ['Remote work always reduces productivity.', 'Employees should never work from home.', 'Evidence challenged concerns about remote-work productivity.', 'Employees are less productive outside the office.'],
    answerKey: 2,
  },
  { level: 'C1', prompt: 'Rarely ___ such a dramatic change in public opinion.', choices: ['we have seen', 'have we seen', 'we saw', 'did we have seen'], answerKey: 1 },
  { level: 'C1', prompt: 'Had the company acted sooner, the problem ___.', choices: ['wouldn’t become', 'wouldn’t have become', 'hadn’t become', 'won’t become'], answerKey: 1 },
  { level: 'C1', prompt: 'It is essential that every applicant ___ the required documents before the deadline.', choices: ['submits', 'submitted', 'submit', 'submitting'], answerKey: 2 },
  { level: 'C1', prompt: 'The politician attempted to ___ concerns about the new policy by emphasizing its long-term benefits.', choices: ['alleviate', 'deteriorate', 'provoke', 'contradict'], answerKey: 0 },
  { level: 'C1', prompt: 'Although the proposal appears financially attractive in the short term, its long-term consequences may ___ any immediate benefits.', choices: ['outweigh', 'undergo', 'withdraw', 'overcome'], answerKey: 0 },
  {
    level: 'C1',
    prompt: 'Although artificial intelligence is often portrayed as a threat to employment, its effect on the labor market is likely to be more nuanced. Certain occupations may disappear, while others will evolve or emerge. Consequently, the more significant challenge may not be widespread unemployment but ensuring that workers acquire the skills required for new roles. What does the writer suggest?',
    choices: ['AI will inevitably cause widespread unemployment.', 'AI will have almost no effect on employment.', 'The main challenge may be helping workers adapt to a changing job market.', 'Companies should avoid using AI.'],
    answerKey: 2,
  },
];

const german: PlacementQuestionSeed[] = [
  { level: 'A1', prompt: 'Ich ___ aus Iran.', choices: ['kommt', 'komme', 'kommen', 'kommst'], answerKey: 1 },
  { level: 'A1', prompt: 'Das ist ___ Bruder.', choices: ['mein', 'meine', 'meinen', 'meiner'], answerKey: 0 },
  { level: 'A1', prompt: 'Wir ___ jeden Tag Deutsch.', choices: ['lernt', 'lernst', 'lernen', 'lerne'], answerKey: 2 },
  { level: 'A1', prompt: 'Wie alt ___ du?', choices: ['bist', 'bin', 'ist', 'sind'], answerKey: 0 },
  { level: 'A1', prompt: 'Er hat ___ Auto.', choices: ['eine', 'einen', 'ein', 'einem'], answerKey: 2 },
  {
    level: 'A1',
    prompt: '„Wie geht es dir?“ Welche Antwort passt am besten?',
    choices: ['Ich bin 25 Jahre alt.', 'Mir geht es gut, danke.', 'Ich komme aus Berlin.', 'Ich heiße Anna.'],
    answerKey: 1,
  },
  { level: 'A2', prompt: 'Seit zwei Jahren ___ ich in Berlin.', choices: ['wohnte', 'wohne', 'habe gewohnt', 'wohnen'], answerKey: 1 },
  { level: 'A2', prompt: 'Gestern ___ wir ins Kino gegangen.', choices: ['haben', 'sind', 'werden', 'waren'], answerKey: 1 },
  { level: 'A2', prompt: 'Ich interessiere mich ___ Musik.', choices: ['an', 'auf', 'für', 'mit'], answerKey: 2 },
  { level: 'A2', prompt: 'Kannst du mir sagen, wann der Zug ___?', choices: ['abfährt', 'fährt ab', 'abfahren', 'abgefahren'], answerKey: 0 },
  { level: 'A2', prompt: 'Wenn das Wetter schön ist, ___ wir spazieren.', choices: ['gingen', 'gehen', 'gegangen', 'würden'], answerKey: 1 },
  { level: 'A2', prompt: 'Ich brauche einen ___ Pullover.', choices: ['warmer', 'warmes', 'warmen', 'warme'], answerKey: 2 },
  { level: 'B1', prompt: 'Wenn ich mehr Zeit hätte, ___ ich öfter reisen.', choices: ['werde', 'würde', 'bin', 'habe'], answerKey: 1 },
  { level: 'B1', prompt: 'Obwohl er sehr müde war, ___ er weitergearbeitet.', choices: ['hat', 'ist', 'wird', 'hatte'], answerKey: 0 },
  { level: 'B1', prompt: 'Das Buch, ___ ich gestern gekauft habe, ist sehr interessant.', choices: ['der', 'den', 'das', 'dem'], answerKey: 2 },
  { level: 'B1', prompt: 'Ich freue mich darauf, dich bald ___.', choices: ['sehen', 'gesehen', 'zu sehen', 'sehe'], answerKey: 2 },
  { level: 'B1', prompt: 'Das Gebäude wurde im Jahr 2005 ___.', choices: ['bauen', 'gebaut', 'gebautet', 'gebauten'], answerKey: 1 },
  { level: 'B1', prompt: 'Was bedeutet „zuverlässig“?', choices: ['jemand, auf den man sich verlassen kann', 'jemand, der immer zu spät kommt', 'jemand, der wenig arbeitet', 'jemand, der schnell wütend wird'], answerKey: 0 },
  { level: 'B2', prompt: 'Nachdem er die Prüfung bestanden ___, begann er mit seinem neuen Job.', choices: ['hat', 'hatte', 'wäre', 'wurde'], answerKey: 1 },
  { level: 'B2', prompt: 'Wäre ich früher informiert worden, ___ ich an der Veranstaltung teilgenommen.', choices: ['werde', 'würde', 'hätte', 'habe'], answerKey: 2 },
  { level: 'B2', prompt: 'Sie behauptet, nichts davon ___.', choices: ['wissen', 'gewusst zu haben', 'wusste', 'gewusst haben'], answerKey: 1 },
  { level: 'B2', prompt: 'Je mehr man eine Sprache übt, ___ wird man beim Sprechen.', choices: ['sicher', 'am sichersten', 'desto sicherer', 'sicherer als'], answerKey: 2 },
  { level: 'B2', prompt: 'Was bedeutet die Wendung „zur Verfügung stehen“?', choices: ['verfügbar sein', 'etwas vermeiden', 'etwas ablehnen', 'sich beschweren'], answerKey: 0 },
  {
    level: 'B2',
    prompt: 'Viele Unternehmen ermöglichen ihren Mitarbeitern inzwischen, teilweise von zu Hause aus zu arbeiten. Befürworter betonen, dass dadurch lange Arbeitswege vermieden werden können und die Beschäftigten häufig flexibler sind. Kritiker weisen jedoch darauf hin, dass der direkte Austausch im Team schwieriger werden kann. Welche Aussage fasst den Text am besten zusammen?',
    choices: ['Homeoffice hat ausschließlich Vorteile.', 'Homeoffice hat sowohl Vorteile als auch Nachteile.', 'Die meisten Arbeitnehmer möchten nicht zu Hause arbeiten.', 'Unternehmen sollten Homeoffice vollständig abschaffen.'],
    answerKey: 1,
  },
  { level: 'C1', prompt: 'Er behauptete, er ___ von den Änderungen nichts gewusst.', choices: ['hat', 'hätte', 'habe', 'hatte'], answerKey: 2 },
  { level: 'C1', prompt: 'Nicht nur ___ die Maßnahme hohe Kosten verursacht, sondern sie hat auch zu erheblichen Verzögerungen geführt.', choices: ['sie hat', 'hat', 'hatte sie', 'sie hatte'], answerKey: 1 },
  { level: 'C1', prompt: 'Die Regierung musste schließlich ___, dass die ursprüngliche Strategie nicht erfolgreich gewesen war.', choices: ['einräumen', 'verhindern', 'verbergen', 'bestreiten'], answerKey: 0 },
  { level: 'C1', prompt: 'Die wiederholten Skandale haben das Vertrauen der Bevölkerung in die Institution erheblich ___.', choices: ['erweitert', 'erleichtert', 'untergraben', 'gewährleistet'], answerKey: 2 },
  { level: 'C1', prompt: '___ der schwierigen wirtschaftlichen Lage entschied sich das Unternehmen gegen weitere Investitionen.', choices: ['In Anbetracht', 'Anstatt', 'Trotz dass', 'Während von'], answerKey: 0 },
  {
    level: 'C1',
    prompt: 'Digitalisierung wird häufig als Mittel zur Steigerung der Effizienz dargestellt. Eine ausschließliche Konzentration auf technische Lösungen greift jedoch zu kurz. Ob digitale Veränderungen tatsächlich erfolgreich sind, hängt ebenso davon ab, ob Organisationen ihre internen Prozesse anpassen und ihre Mitarbeiter angemessen auf neue Arbeitsweisen vorbereiten. Welche Aussage entspricht am besten der Meinung des Autors?',
    choices: ['Technische Lösungen allein garantieren eine erfolgreiche Digitalisierung.', 'Digitalisierung führt normalerweise zu geringerer Effizienz.', 'Erfolgreiche Digitalisierung erfordert neben Technik auch organisatorische Veränderungen.', 'Mitarbeiter spielen bei der Digitalisierung kaum eine Rolle.'],
    answerKey: 2,
  },
];

const french: PlacementQuestionSeed[] = [
  { level: 'A1', prompt: 'Je ___ étudiant.', choices: ['suis', 'es', 'est', 'sont'], answerKey: 0 },
  { level: 'A1', prompt: 'Nous ___ à Paris.', choices: ['habite', 'habitons', 'habitez', 'habitent'], answerKey: 1 },
  { level: 'A1', prompt: 'Elle ___ 25 ans.', choices: ['est', 'fait', 'a', 'va'], answerKey: 2 },
  { level: 'A1', prompt: 'J’aime ___ musique.', choices: ['le', 'la', 'les', 'un'], answerKey: 1 },
  { level: 'A1', prompt: 'Vous ___ français ?', choices: ['parlez', 'parlons', 'parle', 'parlent'], answerKey: 0 },
  { level: 'A1', prompt: '« Comment ça va ? » Quelle réponse est la plus appropriée ?', choices: ['Je m’appelle Marie.', 'J’ai vingt ans.', 'Ça va très bien, merci.', 'Je suis à Paris.'], answerKey: 2 },
  { level: 'A2', prompt: 'Hier, nous ___ au restaurant.', choices: ['mangeons', 'avons mangé', 'mangerons', 'mangions toujours'], answerKey: 1 },
  { level: 'A2', prompt: 'Il n’y a ___ lait dans le frigo.', choices: ['pas de', 'pas du', 'aucun de', 'des'], answerKey: 0 },
  { level: 'A2', prompt: 'Je vais ___ mes amis ce soir.', choices: ['voir', 'vu', 'vois', 'voyant'], answerKey: 0 },
  { level: 'A2', prompt: 'Elle habite ici ___ trois ans.', choices: ['depuis', 'pendant', 'en', 'il y a'], answerKey: 0 },
  { level: 'A2', prompt: 'Ce livre est ___ que l’autre.', choices: ['intéressant', 'plus intéressant', 'le plus intéressant que', 'très plus intéressant'], answerKey: 1 },
  { level: 'A2', prompt: 'Si tu es fatigué, tu ___ te reposer.', choices: ['devrais', 'devais', 'devra', 'avais'], answerKey: 0 },
  { level: 'B1', prompt: 'Si j’avais plus de temps, je ___ davantage.', choices: ['voyage', 'voyagerai', 'voyagerais', 'ai voyagé'], answerKey: 2 },
  { level: 'B1', prompt: 'Quand j’étais enfant, je ___ souvent chez mes grands-parents.', choices: ['vais', 'allais', 'suis allé', 'irai'], answerKey: 1 },
  { level: 'B1', prompt: 'C’est le film ___ je t’ai parlé.', choices: ['que', 'qui', 'dont', 'où'], answerKey: 2 },
  { level: 'B1', prompt: 'Il faut que tu ___ plus attentif.', choices: ['es', 'seras', 'sois', 'serais'], answerKey: 2 },
  { level: 'B1', prompt: 'Elle s’intéresse ___ l’histoire de l’art.', choices: ['à', 'de', 'pour', 'avec'], answerKey: 0 },
  { level: 'B1', prompt: 'Que signifie le mot « fiable » ?', choices: ['difficile à comprendre', 'sur lequel on peut compter', 'très cher', 'peu connu'], answerKey: 1 },
  { level: 'B2', prompt: 'Bien qu’il ___ fatigué, il a continué à travailler.', choices: ['est', 'était', 'soit', 'sera'], answerKey: 2 },
  { level: 'B2', prompt: 'Si j’avais su, je ___ plus tôt.', choices: ['partirais', 'serais parti', 'suis parti', 'partirai'], answerKey: 1 },
  { level: 'B2', prompt: 'Elle affirme ___ ce document auparavant.', choices: ['lire', 'avoir lu', 'lisant', 'de lire'], answerKey: 1 },
  { level: 'B2', prompt: 'Cette mesure vise à ___ les dépenses publiques.', choices: ['réduire', 'empêcher de', 'augmenter à', 'bénéficier'], answerKey: 0 },
  { level: 'B2', prompt: 'Que signifie l’expression « mettre en œuvre » ?', choices: ['abandonner', 'appliquer', 'critiquer', 'retarder'], answerKey: 1 },
  { level: 'B2', prompt: 'De plus en plus d’entreprises permettent à leurs employés de travailler à distance. Cette organisation offre davantage de flexibilité et permet de réduire le temps passé dans les transports. Cependant, certains salariés regrettent le manque de contacts directs avec leurs collègues. Quelle option résume le mieux le texte ?', choices: ['Le télétravail présente uniquement des avantages.', 'Le télétravail est toujours moins efficace.', 'Le télétravail présente à la fois des avantages et des inconvénients.', 'Les salariés refusent généralement de travailler à distance.'], answerKey: 2 },
  { level: 'C1', prompt: 'Quoiqu’il ___ plusieurs difficultés, le projet a finalement abouti.', choices: ['rencontre', 'ait rencontré', 'rencontrait', 'rencontrera'], answerKey: 1 },
  { level: 'C1', prompt: 'Encore faut-il que cette solution ___ réellement efficace.', choices: ['est', 'était', 'soit', 'sera'], answerKey: 2 },
  { level: 'C1', prompt: 'Le gouvernement a dû ___ que les mesures prises n’avaient pas produit les résultats attendus.', choices: ['admettre', 'empêcher', 'nier', 'éviter'], answerKey: 0 },
  { level: 'C1', prompt: 'Cette décision risque de ___ les inégalités déjà existantes.', choices: ['atténuer toujours', 'creuser', 'résoudre de', 'atteindre à'], answerKey: 1 },
  { level: 'C1', prompt: 'Son argumentation est particulièrement ___ : elle repose sur des données précises et une analyse approfondie.', choices: ['superficielle', 'convaincante', 'vague', 'hésitante'], answerKey: 1 },
  { level: 'C1', prompt: 'La transition numérique est souvent présentée comme une solution permettant d’améliorer la productivité. Pourtant, la technologie seule ne suffit pas. Pour qu’une transformation numérique soit réellement efficace, les entreprises doivent également repenser leur organisation, former leurs salariés et adapter leurs méthodes de travail. Quelle option exprime le mieux le point de vue de l’auteur ?', choices: ['La technologie suffit à garantir le succès d’une transformation numérique.', 'La transformation numérique nécessite aussi des changements humains et organisationnels.', 'La productivité diminue toujours avec la technologie.', 'La formation des employés est inutile.'], answerKey: 1 },
];

export const studentPlacementQuestionBanks = { en: english, de: german, fr: french } as const;
