'use client';

import {useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {BookOpen,ChevronDown,ChevronUp,Plus,Trash2} from 'lucide-react';
import {api,ApiError} from '@/lib/api';
import {useTranslations} from './locale-provider';

type Question={id:string;prompt:{fa?:string;en?:string};type:string;points:number;order:number};
type Section={id:string;skill:string;title:string;durationMinutes:number;order:number;questions:Question[]};
type Test={id:string;slug:string;titleFa:string;titleEn:string;published:boolean;sections:Section[]};
const input='w-full rounded-xl border border-[#dce1ee] bg-white px-3.5 py-3 outline-none transition focus:border-purple focus:ring-4 focus:ring-violet/10';
const value=(form:FormData,key:string)=>String(form.get(key)??'').trim();

export function AdminTestManager(){
 const{locale}=useTranslations(),fa=locale==='fa',qc=useQueryClient(),[selected,setSelected]=useState<string>(),[expanded,setExpanded]=useState<string>();
 const query=useQuery({queryKey:['admin-tests'],queryFn:()=>api<Test[]>('/admin/tests')}),tests=query.data??[],active=useMemo(()=>tests.find(test=>test.id===(selected??tests[0]?.id)),[tests,selected]);
 const mutation=useMutation({mutationFn:(task:()=>Promise<unknown>)=>task(),onSuccess:async()=>{await qc.invalidateQueries({queryKey:['admin-tests']})}});
 const message=mutation.error?<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{mutation.error instanceof ApiError?mutation.error.message:fa?'عملیات ناموفق بود.':'The operation failed.'}</p>:mutation.isSuccess?<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{fa?'تغییرات ذخیره شد.':'Changes saved.'}</p>:null;
 return <section><header className="mb-7"><p className="text-sm font-bold text-purple">{fa?'ساخت ساده آزمون':'Simple test builder'}</p><h1 className="mt-2 text-3xl font-black">{fa?'آزمون‌ها و سؤال‌ها':'Tests & questions'}</h1><p className="mt-2 text-sm text-muted">{fa?'آزمون را بسازید، یک مهارت را باز کنید و سؤال‌ها را یکی‌یکی وارد کنید. چهار بخش استاندارد خودکار ساخته می‌شوند.':'Create a test, open a skill and add questions one at a time. Four standard sections are created automatically.'}</p></header>
 <div className="grid gap-6 xl:grid-cols-[340px_1fr]"><aside className="space-y-5"><form className="panel-card p-5" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);mutation.mutate(()=>api('/admin/tests/simple',{method:'POST',body:JSON.stringify({titleFa:value(form,'titleFa'),titleEn:value(form,'titleEn'),durationMinutes:Number(value(form,'durationMinutes'))||164})}))}}><h2 className="flex items-center gap-2 font-black"><Plus size={18}/>{fa?'آزمون جدید':'New test'}</h2><p className="mt-2 text-xs leading-6 text-muted">{fa?'فقط عنوان را وارد کنید؛ ساختار آزمون آماده می‌شود.':'Enter the titles and the structure will be ready.'}</p><div className="mt-4 grid gap-3"><input className={input} name="titleFa" placeholder="عنوان فارسی" required/><input className={input} name="titleEn" dir="ltr" placeholder="English title" required/><input className={input} name="durationMinutes" type="number" min="1" defaultValue="164" aria-label={fa?'زمان آزمون به دقیقه':'Duration in minutes'}/><button className="brand-gradient rounded-xl py-3 font-black text-white" disabled={mutation.isPending}>{fa?'ساخت آزمون':'Create test'}</button></div>{message}</form><div className="panel-card overflow-hidden p-2"><p className="px-3 py-3 text-xs font-bold text-muted">{fa?'آزمون‌های موجود':'Existing tests'}</p>{query.isLoading?<div className="skeleton h-24 rounded-xl"/>:tests.length?tests.map(test=><button key={test.id} onClick={()=>setSelected(test.id)} className={`mb-1 w-full rounded-xl p-3 text-start ${active?.id===test.id?'bg-lavender text-purple':'hover:bg-[#f6f7fb]'}`}><strong className="block text-sm">{fa?test.titleFa:test.titleEn}</strong><small className="mt-1 flex items-center justify-between text-muted"><span>{test.sections.reduce((sum,section)=>sum+section.questions.length,0)} {fa?'سؤال':'questions'}</span><span className={test.published?'text-emerald-600':'text-orange-500'}>{test.published?(fa?'منتشرشده':'Published'):(fa?'پیش‌نویس':'Draft')}</span></small></button>):<p className="p-5 text-center text-sm text-muted">{fa?'هنوز آزمونی ساخته نشده است.':'No tests yet.'}</p>}</div></aside>
 <main>{active?<div className="space-y-5"><article className="panel-card p-5 md:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{fa?active.titleFa:active.titleEn}</h2><p className="latin mt-1 text-sm text-muted">/{active.slug}</p></div><div className="flex gap-2"><button onClick={()=>mutation.mutate(()=>api(`/admin/tests/${active.id}`,{method:'PATCH',body:JSON.stringify({published:!active.published})}))} className={`rounded-xl px-4 py-2.5 text-sm font-black ${active.published?'bg-orange-50 text-orange-600':'bg-emerald-50 text-emerald-700'}`}>{active.published?(fa?'لغو انتشار':'Unpublish'):(fa?'انتشار آزمون':'Publish')}</button><button aria-label={fa?'حذف آزمون':'Delete test'} onClick={()=>confirm(fa?'آزمون حذف شود؟':'Delete this test?')&&mutation.mutate(()=>api(`/admin/tests/${active.id}`,{method:'DELETE'}))} className="grid size-10 place-items-center rounded-xl bg-red-50 text-red-600"><Trash2 size={18}/></button></div></div>{message}</article>{active.sections.map(section=><SectionCard key={section.id} section={section} open={expanded===section.id} toggle={()=>setExpanded(expanded===section.id?undefined:section.id)} mutate={task=>mutation.mutate(task)} fa={fa}/>)}</div>:<div className="panel-card grid min-h-80 place-items-center p-8 text-center"><div><BookOpen className="mx-auto text-purple" size={42}/><p className="mt-4 text-muted">{fa?'یک آزمون بسازید یا انتخاب کنید.':'Create or select a test.'}</p></div></div>}</main></div></section>
}

function SectionCard({section,open,toggle,mutate,fa}:{section:Section;open:boolean;toggle:()=>void;mutate:(task:()=>Promise<unknown>)=>void;fa:boolean}){return <article className="panel-card overflow-hidden"><button onClick={toggle} className="flex w-full items-center gap-4 p-5 text-start"><span className="brand-gradient grid size-11 place-items-center rounded-xl font-black text-white">{section.order}</span><span className="flex-1"><strong className="block">{section.title}</strong><small className="latin text-muted">{section.skill} · {section.questions.length} questions · {section.durationMinutes} min</small></span>{open?<ChevronUp/>:<ChevronDown/>}</button>{open&&<div className="border-t hairline p-5"><QuestionCreator section={section} mutate={mutate} fa={fa}/><div className="mt-5 overflow-x-auto rounded-xl border hairline"><table className="w-full min-w-[680px] text-sm"><thead className="bg-[#f7f8fc] text-muted"><tr><th className="p-3 text-start">#</th><th className="p-3 text-start">{fa?'سؤال فارسی':'English question'}</th><th className="p-3 text-start">{fa?'نوع':'Type'}</th><th className="p-3 text-start">{fa?'امتیاز':'Points'}</th><th className="p-3"/></tr></thead><tbody className="divide-y hairline">{section.questions.map(question=><tr key={question.id}><td className="p-3 latin">{question.order}</td><td className="p-3"><strong className="block">{fa?question.prompt.fa:question.prompt.en}</strong><small dir={fa?'ltr':'rtl'} className="mt-1 block text-muted">{fa?question.prompt.en:question.prompt.fa}</small></td><td className="p-3 latin">{question.type}</td><td className="p-3 latin">{question.points}</td><td className="p-3 text-end"><button aria-label={fa?'حذف سؤال':'Delete question'} onClick={()=>confirm(fa?'سؤال حذف شود؟':'Delete question?')&&mutate(()=>api(`/admin/tests/questions/${question.id}`,{method:'DELETE'}))} className="text-red-500"><Trash2 size={17}/></button></td></tr>)}{!section.questions.length&&<tr><td colSpan={5} className="p-6 text-center text-muted">{fa?'سؤالی ثبت نشده است.':'No questions yet.'}</td></tr>}</tbody></table></div></div>}</article>}

function QuestionCreator({section,mutate,fa}:{section:Section;mutate:(task:()=>Promise<unknown>)=>void;fa:boolean}){
 const[type,setType]=useState('single_choice'),objective=['single_choice','multiple_choice'].includes(type),withAnswer=objective||type==='true_false';
 return <form className="rounded-2xl bg-[#f8f9fd] p-4 md:p-5" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget),lines=(key:string)=>value(form,key).split(/\r?\n/).map(item=>item.trim()).filter(Boolean),choices=objective?{fa:lines('choicesFa'),en:lines('choicesEn')}:undefined,raw=value(form,'answerKey'),answerKey=type==='multiple_choice'?raw.split(',').map(item=>Number(item.trim())-1).filter(Number.isInteger):withAnswer?Number(raw)-1:undefined;mutate(()=>api(`/admin/tests/sections/${section.id}/questions`,{method:'POST',body:JSON.stringify({prompt:{fa:value(form,'promptFa'),en:value(form,'promptEn')},type,choices,answerKey,points:1,order:section.questions.length+1})}))}}><div className="flex items-start justify-between gap-4"><div><h4 className="font-black">{fa?'ثبت سؤال جدید':'Add a new question'}</h4><p className="mt-1 text-xs text-muted">{fa?'هر بار یک سؤال ثبت می‌شود و ترتیب خودکار است.':'Questions are added one at a time and ordered automatically.'}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs text-purple">{section.questions.length+1}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><label><span className="mb-2 block text-xs font-bold">{fa?'نوع سؤال':'Question type'}</span><select value={type} onChange={event=>setType(event.target.value)} className={input}><option value="single_choice">{fa?'تک‌گزینه‌ای':'Single choice'}</option><option value="multiple_choice">{fa?'چندگزینه‌ای':'Multiple choice'}</option><option value="true_false">{fa?'درست / نادرست':'True / false'}</option><option value="short_text">{fa?'پاسخ کوتاه':'Short answer'}</option><option value="essay">{fa?'پاسخ تشریحی':'Essay'}</option><option value="recording">{fa?'پاسخ صوتی':'Voice answer'}</option></select></label><div/><TextArea name="promptFa" label={fa?'متن فارسی سؤال':'Persian question'} required/><TextArea name="promptEn" label={fa?'متن انگلیسی سؤال':'English question'} dir="ltr" required/>{objective&&<><TextArea name="choicesFa" label={fa?'گزینه‌های فارسی؛ هر گزینه یک خط':'Persian choices; one per line'} required/><TextArea name="choicesEn" label={fa?'گزینه‌های انگلیسی؛ هر گزینه یک خط':'English choices; one per line'} dir="ltr" required/></>}{withAnswer&&<label className="md:col-span-2"><span className="mb-2 block text-xs font-bold">{type==='multiple_choice'?(fa?'شماره گزینه‌های صحیح، مثل ۱،۳':'Correct option numbers, e.g. 1,3'):(fa?'شماره گزینه صحیح':'Correct option number')}</span>{type==='true_false'?<select name="answerKey" className={input} required><option value="1">{fa?'درست':'True'}</option><option value="2">{fa?'نادرست':'False'}</option></select>:<input name="answerKey" dir="ltr" className={input} placeholder={type==='multiple_choice'?'1,3':'1'} required/>}</label>}<button className="brand-gradient rounded-xl py-3 font-black text-white md:col-span-2"><Plus className="inline" size={17}/> {fa?'ثبت این سؤال':'Add this question'}</button></div></form>
}

function TextArea({name,label,dir,required}:{name:string;label:string;dir?:'ltr';required?:boolean}){return <label><span className="mb-2 block text-xs font-bold">{label}</span><textarea name={name} dir={dir} className={`${input} min-h-28`} required={required}/></label>}
