'use client';
import {useEffect,useId,useMemo,useRef,useState} from 'react';
import {useInfiniteQuery} from '@tanstack/react-query';
import {Check,ChevronDown,LoaderCircle,Search,X} from 'lucide-react';
import {api,type ItemsPage} from '@/lib/api';
import {useTranslations} from './locale-provider';

type Option={id:string;label:string;description?:string};
type Props={entity:'users'|'teachers'|'tests'|'passages'|'bookings'|'payments'|'roles'|'languages'|'support-agents';value:Option|null;onChange:(value:Option|null)=>void;placeholder?:string;disabled?:boolean;className?:string;name?:string};
export function AsyncSearchSelect({entity,value,onChange,placeholder,disabled,className='',name}:Props){
 const {locale}=useTranslations(),fa=locale==='fa',id=useId(),root=useRef<HTMLDivElement>(null),[open,setOpen]=useState(false),[input,setInput]=useState(''),[query,setQuery]=useState(''),[active,setActive]=useState(0);
 useEffect(()=>{const timer=setTimeout(()=>setQuery(input.trim()),300);return()=>clearTimeout(timer)},[input]);
 useEffect(()=>{const close=(event:MouseEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 const result=useInfiniteQuery({queryKey:['async-select',entity,query],initialPageParam:1,queryFn:({pageParam})=>api<ItemsPage<Option>>(`/search/${entity}?q=${encodeURIComponent(query)}&page=${pageParam}&pageSize=20`),getNextPageParam:last=>last.pagination.hasMore?last.pagination.page+1:undefined,enabled:open&&!disabled,staleTime:30_000});
 const options=useMemo(()=>result.data?.pages.flatMap(page=>page.items)??[],[result.data]);
 useEffect(()=>setActive(0),[query,open]);
 const choose=(option:Option)=>{onChange(option);setOpen(false);setInput('')};
 const keyDown=(event:React.KeyboardEvent)=>{if(!open&&(event.key==='ArrowDown'||event.key==='Enter')){setOpen(true);event.preventDefault();return}if(!open)return;if(event.key==='ArrowDown'){setActive(index=>Math.min(options.length-1,index+1));event.preventDefault()}if(event.key==='ArrowUp'){setActive(index=>Math.max(0,index-1));event.preventDefault()}if(event.key==='Enter'&&options[active]){choose(options[active]);event.preventDefault()}if(event.key==='Escape'){setOpen(false);event.preventDefault()}};
 return <div ref={root} className={`relative ${className}`} onKeyDown={keyDown}>{name&&<input type="hidden" name={name} value={value?.id??''}/>}<button type="button" disabled={disabled} aria-haspopup="listbox" aria-expanded={open} aria-controls={`${id}-list`} onClick={()=>setOpen(v=>!v)} className="input flex w-full items-center gap-3 text-start disabled:opacity-60"><Search size={17} className="text-muted"/><span className={`min-w-0 flex-1 truncate ${value?'font-bold':'text-muted'}`}>{value?.label??placeholder??(fa?'جستجو و انتخاب…':'Search and select…')}</span>{value&&<span role="button" tabIndex={0} aria-label={fa?'پاک کردن':'Clear'} onClick={event=>{event.stopPropagation();onChange(null)}} className="grid size-7 place-items-center rounded-lg hover:bg-black/5"><X size={15}/></span>}<ChevronDown size={16} className={`transition ${open?'rotate-180':''}`}/></button>{open&&<div className="absolute z-50 mt-2 w-full overflow-hidden rounded-2xl border hairline bg-white shadow-2xl"><div className="border-b hairline p-3"><div className="flex items-center gap-2 rounded-xl bg-[#f5f6fa] px-3"><Search size={16}/><input autoFocus value={input} onChange={e=>setInput(e.target.value)} placeholder={fa?'نام، موبایل یا ایمیل…':'Name, phone, or email…'} className="w-full bg-transparent py-3 outline-none"/></div></div><div id={`${id}-list`} role="listbox" className="max-h-72 overflow-auto p-2">{result.isLoading&&<div className="flex items-center justify-center gap-2 p-7 text-sm text-muted"><LoaderCircle className="animate-spin" size={18}/>{fa?'در حال جستجو…':'Searching…'}</div>}{result.isError&&<div className="p-5 text-sm text-red-700">{fa?'جستجو ناموفق بود. دوباره تلاش کنید.':'Search failed. Try again.'}</div>}{!result.isLoading&&!options.length&&<div className="p-7 text-center text-sm text-muted">{fa?'موردی پیدا نشد. عبارت دیگری بنویسید.':'No results. Try another search.'}</div>}{options.map((option,index)=><button type="button" role="option" aria-selected={value?.id===option.id} key={option.id} onMouseEnter={()=>setActive(index)} onClick={()=>choose(option)} className={`flex w-full items-start gap-3 rounded-xl p-3 text-start ${index===active?'bg-[#eef2ff]':''}`}><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{option.label}</strong>{option.description&&<small className="mt-1 block truncate text-muted">{option.description}</small>}</span>{value?.id===option.id&&<Check size={17} className="text-blue"/>}</button>)}{result.hasNextPage&&<button type="button" disabled={result.isFetchingNextPage} onClick={()=>result.fetchNextPage()} className="mt-1 w-full rounded-xl p-3 text-sm font-bold text-blue">{result.isFetchingNextPage?(fa?'در حال دریافت…':'Loading…'):(fa?'نمایش موارد بیشتر':'Load more')}</button>}</div></div>}</div>
}
