'use client';
import Link from 'next/link';
import {BadgeCheck,Star,UserRound} from 'lucide-react';
import type{PublicTeacher}from '@/lib/api';
import{useTranslations}from'./locale-provider';
import{localePath}from'@/lib/i18n';

export function TeacherCard({teacher,reason,score}:{teacher:PublicTeacher;reason?:string;score?:number}){
 const{locale}=useTranslations(),fa=locale==='fa',initials=teacher.nameEn.split(' ').map(n=>n[0]).join('').slice(0,2),money=new Intl.NumberFormat(fa?'fa-IR':'en-US').format(teacher.trialPrice)+(fa?' تومان':' IRR');
 return <article className="surface-card lift relative overflow-hidden p-5">{score!=null&&<span className="absolute start-4 top-4 z-10 rounded-full bg-lavender px-3 py-1 text-xs font-black text-purple">{score}% {fa?'تطبیق':'match'}</span>}<div className="flex items-start gap-4"><div className="relative grid size-24 shrink-0 place-items-center overflow-hidden rounded-[20px] bg-gradient-to-br from-[#e7ecff] to-[#eee7ff]"><UserRound size={46} className="text-purple/55"/><span className="latin absolute bottom-2 text-xs font-black text-navy/50">{initials}</span></div><div className="min-w-0 flex-1"><h3 className="flex items-center gap-2 text-lg font-black">{fa?teacher.nameFa:teacher.nameEn}<BadgeCheck size={18} className="text-blue"/></h3><p className="mt-1 truncate text-xs text-muted">{fa?teacher.nameEn:teacher.nameFa}</p><p className="mt-3 flex items-center gap-1 text-sm font-bold"><Star size={15} fill="#f5a623" className="text-[#f5a623]"/>{teacher.rating}<span className="font-normal text-muted">({teacher.reviewsCount})</span></p></div></div><p className="mt-5 line-clamp-2 min-h-14 text-sm leading-7 text-muted">{fa?teacher.bioFa:(teacher.bioEn??teacher.bioFa)}</p>{reason&&<p className="mt-4 rounded-xl bg-lavender p-3 text-xs font-bold text-purple">{reason}</p>}<div className="mt-4 flex flex-wrap gap-2">{teacher.specialties.slice(0,3).map(s=><span key={s} className="latin rounded-full bg-[#f4f5f8] px-3 py-1 text-[11px] text-muted">{s}</span>)}</div><div className="mt-5 flex items-end justify-between border-t hairline pt-5"><div><p className="text-xs text-muted">{fa?'جلسه آزمایشی':'Trial lesson'}</p><p className="mt-1 font-black text-blue">{money}</p></div><Link href={localePath(`/teachers/${teacher.slug}`,locale)} className="rounded-xl border border-blue px-4 py-2.5 text-sm font-bold text-blue hover:bg-blue hover:text-white">{fa?'مشاهده و رزرو':'View & book'}</Link></div></article>
}
