export {
  defaultLandingConfig,
  mediaReference,
  normalizeLandingConfig,
  localizedText,
  sectionStyle,
  normalizeTheme,
  typographyStyle,
  SITE_FONTS,
  HEADING_WEIGHTS,
  type SiteFont,
  type LandingConfig,
  type LandingSectionId,
  type LocaleText,
  type SectionStyle,
} from './landing-config';
