import {BadRequestException,HttpException,HttpStatus,Injectable,UnauthorizedException} from '@nestjs/common';
import {JwtService} from '@nestjs/jwt';import{createHash,randomBytes,randomUUID,timingSafeEqual}from'crypto';
import{PrismaService}from'../../prisma.service';import{config}from'../../config';import{SmsService}from'./sms.service';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');const limited=(message:string)=>new HttpException(message,HttpStatus.TOO_MANY_REQUESTS);
@Injectable()export class AuthService{constructor(private db:PrismaService,private jwt:JwtService,private sms:SmsService){}
 async requestOtp(phone:string,_ip?:string){const recent=await this.db.otpChallenge.findFirst({where:{phone,createdAt:{gte:new Date(Date.now()-10*60e3)}},orderBy:{createdAt:'desc'}});if(recent&&recent.resendAfter>new Date())throw limited(`Resend available at ${recent.resendAfter.toISOString()}`);const count=await this.db.otpChallenge.count({where:{phone,createdAt:{gte:new Date(Date.now()-60*60e3)}}});if(count>=5)throw limited('Hourly OTP limit reached');const code=config().NODE_ENV==='production'?String(Math.floor(100000+Math.random()*900000)):'123456';const user=await this.db.user.upsert({where:{phone},update:{},create:{phone,roles:{create:{role:'STUDENT'}}}});const challenge=await this.db.otpChallenge.create({data:{phone,userId:user.id,codeHash:hash(code),expiresAt:new Date(Date.now()+2*60e3),resendAfter:new Date(Date.now()+60e3)}});const sent=await this.sms.sendOtp(phone,code,user.id);return{challengeId:challenge.id,expiresIn:120,resendIn:60,...(sent.developmentCode&&{developmentCode:sent.developmentCode})}}
 async verifyOtp(challengeId:string,phone:string,code:string,meta:{ip?:string;userAgent?:string}){const challenge=await this.db.otpChallenge.findUnique({where:{id:challengeId}});if(!challenge||challenge.phone!==phone||challenge.verifiedAt||challenge.expiresAt<new Date())throw new BadRequestException('OTP expired or invalid');if(challenge.attempts>=5)throw limited('OTP attempts exceeded');const valid=timingSafeEqual(Buffer.from(challenge.codeHash),Buffer.from(hash(code)));if(!valid){await this.db.otpChallenge.update({where:{id:challenge.id},data:{attempts:{increment:1}}});throw new BadRequestException('Incorrect OTP')}await this.db.otpChallenge.update({where:{id:challenge.id},data:{verifiedAt:new Date()}});return this.createSession(challenge.userId!,meta)}
 private async createSession(userId:string,meta:{ip?:string;userAgent?:string},familyId:string=randomUUID()){const user=await this.db.user.findUniqueOrThrow({where:{id:userId},include:{roles:{include:{permissions:{include:{permission:true}}}}}});if(user.status!=='ACTIVE')throw new UnauthorizedException('Account unavailable');const roles=user.roles.map(r=>r.role);const permissions=[...new Set(user.roles.flatMap(r=>r.permissions.map(p=>p.permission.key)))];const sessionId=randomUUID(),refreshSecret=randomBytes(32).toString('base64url'),refreshToken=`${sessionId}.${refreshSecret}`;await this.db.refreshSession.create({data:{id:sessionId,userId,familyId,tokenHash:hash(refreshSecret),expiresAt:new Date(Date.now()+30*864e5),ip:meta.ip,userAgent:meta.userAgent}});const accessToken=await this.jwt.signAsync({id:user.id,roles,permissions,sessionId});return{accessToken,refreshToken,expiresIn:900,user:{id:user.id,phone:user.phone,name:user.name,locale:user.locale,timezone:user.timezone,profileComplete:user.profileComplete,roles,permissions}}}
 async refresh(token:string,meta:{ip?:string;userAgent?:string}){const[id,secret]=token.split('.');if(!id||!secret)throw new UnauthorizedException();const session=await this.db.refreshSession.findUnique({where:{id}});if(!session||session.revokedAt||session.expiresAt<new Date()||hash(secret)!==session.tokenHash){if(session)await this.revokeFamily(session.familyId);throw new UnauthorizedException('Refresh token reuse or expiry')}const next=await this.createSession(session.userId,meta,session.familyId);await this.db.refreshSession.update({where:{id},data:{revokedAt:new Date(),replacedById:next.refreshToken.split('.')[0]}});return next}
 async logout(token:string){const id=token.split('.')[0];if(id)await this.db.refreshSession.updateMany({where:{id},data:{revokedAt:new Date()}});return{ok:true}}revokeFamily(familyId:string){return this.db.refreshSession.updateMany({where:{familyId,revokedAt:null},data:{revokedAt:new Date()}})}}
